/// Flutter icons Workout
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Workout
///      fonts:
///       - asset: fonts/Workout.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Workout {
  Workout._();

  static const _kFontFam = 'Workout';
  static const String? _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulse = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
